//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nvv.Lesson10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nvvKetqua
    {
        public string NvvMaSV { get; set; }
        public string NvvMaKH { get; set; }
        public Nullable<double> Diem { get; set; }
    }
}
