//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nvv.Lesson10.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NvvK22CNT2Lesson10DbEntities : DbContext
    {
        public NvvK22CNT2Lesson10DbEntities()
            : base("name=NvvK22CNT2Lesson10DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<nvvKetqua> nvvKetqua { get; set; }
        public virtual DbSet<nvvKhoa> nvvKhoa { get; set; }
        public virtual DbSet<nvvMonHoc> nvvMonHoc { get; set; }
        public virtual DbSet<nvvSinhVien> nvvSinhVien { get; set; }
    }
}
