//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NvvBaiKiemTraGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nvvSinhVien
    {
        public string NvvMaSV { get; set; }
        public string NvvHoSV { get; set; }
        public string NvvTenSV { get; set; }
        public Nullable<System.DateTime> NvvNgaySinh { get; set; }
        public Nullable<bool> NvvPhai { get; set; }
        public string NvvPhone { get; set; }
        public string NvvEmail { get; set; }
        public string NvvMaKH { get; set; }
    }
}
